name       : baloo
version    : 5.79.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/baloo-5.79.0.tar.xz : 80f9aca313fc214b6363ae37546df7825eafdb291bdc6f597d86cb0b8c38ff50
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
