name       : baloo
version    : 5.64.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/baloo-5.64.0.tar.xz : adaaef1aeec07ccc210210a2e67f4d12c0275226bb05d0220da0281f1a3984c2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
