name       : baloo
version    : 5.63.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/baloo-5.63.0.tar.xz : 90ad2f2e13a33b74030fb4b26e46aa699525009efe30cf0c09283dfa52d818e2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
