name       : baloo
version    : 5.50.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/baloo-5.50.0.tar.xz : c6bb8b65e8b1428b35fe0324b0da1416262e6e0b47386ea755a0855fc502c91e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
    - solid-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
