name       : baloo
version    : 5.77.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/baloo-5.77.0.tar.xz : 00cca6a11b48d6e5cf915d56959ed9087fa9264a8bdc771fc5e5aa5a105bc9db
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
optimize   : lto
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - kwindowsystem-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
