name       : baloo
version    : 5.105.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/baloo-5.105.0.tar.xz : 8d3f7e1acabf6993d2e724b8318c270d66812f5295ae66047c19b3ec5ab1f4c5
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
