name       : baloo
version    : 5.71.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/baloo-5.71.0.tar.xz : 23378213d00ecf1f26eeb417987984f5a63bbd643359403dfd20638cbc1ec84b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
optimize   : lto
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - kwindowsystem-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
