name       : baloo
version    : 5.91.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/baloo-5.91.0.tar.xz : 7574d63379c41d8cb0e6579a0d73ab4257967ecbfaa7affa01472dcca35a12b3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcrash-devel
    - kdbusaddons-devel
    - kfilemetadata-devel
    - kidletime-devel
    - kio-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kfilemetadata-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
